version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=qocwkkooogcck04scc8scgg8
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=y4rTnzRk53Brge6ogc0Nh1XQr2WrNWNQtBQw5Y9ckU0ILB1gekrhzDeSu4Q1Nkyq
      - DB_DATABASE=postgres
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - NODE_ENV=production
      - PORT=3000
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - UPLOAD_DESTINATION=${UPLOAD_DESTINATION}
      - WASABI_ACCESS_KEY=${WASABI_ACCESS_KEY}
      - WASABI_SECRET_KEY=${WASABI_SECRET_KEY}
      - WASABI_BUCKET=${WASABI_BUCKET}
      - WASABI_REGION=${WASABI_REGION}
      - WASABI_ENDPOINT=${WASABI_ENDPOINT}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - app-network
    volumes:
      - uploads:/app/uploads

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
